### ISSUE TITLE
I run your nnpcr.py and get a problem! Can you help me?

### ISSUE THREAD

**Issue by weiluncong** [bakwc/PornDetector#12]
`Traceback (most recent call last):
  File "E:/Python/PornDetector-master/test.py", line 3, in <module>
    model = NNPCR()
  File "E:\Python\PornDetector-master\nnpcr.py", line 257, in __init__
    self.__est = Estimator()
  File "E:\Python\PornDetector-master\nnpcr.py", line 204, in __init__
    b_fc1 = tf.get_variable('b_fc1', [1024], initializer=init_ops.zeros_initializer)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1034, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 933, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 356, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 341, in _true_getter
    use_resource=use_resource)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 711, in _get_single_variable
    validate_shape=validate_shape)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 197, in __init__
    expected_shape=expected_shape)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 275, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 687, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
TypeError: __init__() got multiple values for argument 'dtype'`
I don't change your code anyway. Maybe the problem about initializer?

**Comment by bakwc** [comment]
May be we use different versions of tensorflow? I haven't yet upgraded this project to the latest version, I use tensorflow 0.10 here.

**Comment by weiluncong** [comment]
thank you for your answer, I update my tensorflow from 1.0.0 to 1.3.0 to solve the problem.
I find a question that if the person without the Upper body clothes，the output always is 1.Is this about the dataset to train the moduel?
Can you give me some advice?

**Comment by bakwc** [comment]
Yep, you can fix it with gathering your own dataset and train over it.
