### ISSUE TITLE
mac run error:UnicodeDecodeError: 'ascii' codec can't decode byte 0xbc in position 24: ordinal not in range(128)

### ISSUE THREAD

**Issue by gclsoft** [bakwc/PornDetector#17]
```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/apple/PycharmProjects/face/face_recognition/examples/porn/pornDect.py", line 4, in <module>
    model.loadModel('model.bin')
  File "/Users/apple/PycharmProjects/face/face_recognition/examples/porn/pcr.py", line 156, in loadModel
    data = pickle.loads(data)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbc in position 24: ordinal not in range(128)
```

**Comment by MNCTTY** [comment]
`        data = pickle.loads(data, encoding = 'latin1')`
